update-time: 5

messages:
  - top: "§6ZyberPE Network"
    bottom: "§fWelcome to the server"

  - top: "§bStore"
    bottom: "§fstore.example.com"

  - top: "§aDiscord"
    bottom: "§fJoin our community"
